#!/bin/bash


GIT_HTTP_PROTOCOL="http://"
GIT_SSH_PROTOCOL="git@"
GIT_SERVER="git.schuerz.at"
GIT_REPOPATH="/public/server-config.git"
GIT_SSH_PATH="/srv/repos"
SC=server-config
SCONF="${HOME}/${SC}"
LOGDIR="./logs"
LOGFILE="${LOGDIR}/git.log"
[ -d "${LOGDIR}" ] || mkdir -p "${LOGDIR}"
[ -f "${SCONF}/serverconfig.local.conf" ] && . "${SCONF}/serverconfig.local.conf"

sync_config () {
    cd  "${SCONF}"
    if which git >/dev/null; then
        echo -n "Sync config with ${GIT_SERVER}: " 1>&2
    	#git pull > /dev/null 2>&1
        # GITCHECKOUT_SCRIPT_OPTIONS are options for bin/git-checkout.sh
        # this are now:
        #   -h for headless repo
        ./bin/git-checkout.sh ${GITCHECKOUT_SCRIPT_OPTIONS} || nok="not " 2>>"${LOGFILE}" 1>&2 #|tee -a ./logs/git.log 1>&2   
        #echo -n synced 1>&2
        printf '%s\n' "${nok}synced" 1>&2

cat << EOF

---------------------------------------------------
if you want to update submodules, change dir an run
cd ~/server-config
git submodule update --remote --merge
cd ~
---------------------------------------------------
EOF
#        # Sync submodules
#        #if [ $(curl -sLI --connect-timeout 1 -m 1 "${GIT_HTTP_PROTOCOL}${GIT_SERVER}"|grep "HTTP/"|tail -n1|cut -d$' ' -f2 ) -eq 200 ] ;then 
#        if $( git ls-remote >/dev/null 2>&1) ;then 
#        #if $( git ls-remote https://github.com/VundleVim/Vundle.vim HEAD >/dev/null 2>&1) ;then 
#
#            echo -n "Sync submodules: " 1>&2
#            git submodule update --remote --merge >/dev/null 2>&1 || nok="not " 2>>"${LOGFILE}" 1>&2
#            printf '%s\n' "${nok}synced" 1>&2
#        else
#            echo "Syncing of submodules not possible, github.com not reachable"
#        fi

    else
        echo "git not installed, no configuration possible, please install git" >&2
    	#curl --request GET 'https://git.ebcont.com/jakobus.schuerz/server-config/repository/master/archive.tar.gz'
    fi
    cd ${HOME}
}

. ${SCONF}/functions.sh

cd  "${SCONF}"
#if $(ping -W 1 -c 1 github.com > /dev/null 2>&1) ;then 
#if [ $(curl -sLI --connect-timeout 1 -m 1 "${GIT_HTTP_PROTOCOL}${GIT_SERVER}" |grep "HTTP/"|tail -n1|cut -d$' ' -f2 ) -eq 200 ] ;then 
if $( git ls-remote >/dev/null  2>&1) ;then 
    if [ -d "${SCONF}" ]; then
        sync_config
        create_symlinks "$SCONF"
    else
        echo "Create Server-Config and configure git"
        git clone "${GIT_HTTP_PROTOCOL}${GIT_SERVER}${GIT_REPOPATH}" 2>>"${LOGFILE}"
        #git clone "https://github.com/xundeenergie/server-config.git"
        
        cd  "${SCONF}"

        # Initialize Vundle as preconfigured Submodule
        git submodule update --init --recursive

        USERNAME="jakobus.schuerz"
        FULLNAME="Jakobus Schürz"
        
        git config user.email ${USERNAME}
        git config user.name ${FULLNAME}

        #git config push.default simple
        git remote set-url origin --add "${GIT_SSH_PROTOCOL}${GIT_SERVER}:${GIT_SSH_PATH}${GIT_REPOPATH}"
	


        #git config credential.helper 'store'
        
        sync_config
        
        create_symlinks "$SCONF"

        # Install vim Plugins
        #echo "Run Vim, and in Vim run :PluginInstall to install all Plugins"
        vim -c "PluginInstall" -c ":qa!"
    fi
else 
    echo "${GIT_SERVER}" not reachable >&2;
    echo profile not syncing >&2;
fi

if [ -e "${SCONF}/bashrc_local" ]; then
        . "${SCONF}/bashrc_local"
fi

[ -z "$XDG_RUNTIME_DIR" ] && export XDG_RUNTIME_DIR=/run/user/$(id -u $USER)
if test $SSH_TTY && test $TERM != screen && test $(systemctl status screen@${USER} 1>/dev/null 2>&1; echo $? ) -eq 0; then
        echo Starting or resuming screen session
        echo Press CTRL+C to cancel screen startup
        echo "User: $USER - $UID"
        #systemctl --user start vnc@5901.service
        sleep 2
        screen -UxR
fi

cd ${HOME}
