#!/bin/bash


function _kerberosconfig() {
    KEYS=""
    for KEY_DIR in ${KERBEROS_CONFIG_DIRS[*]};do
        KEYS="${KEYS} $(find ${KERBEROS_CONFIG_DIRS[*]} -type f -name "*.conf" -exec basename {} \; 2>/dev/null |sed 's/\.conf$//' )"
    done
    echo $KEYS
#    echo $(find ${KERBEROS_CONFIG_DIRS[*]} -type f -name "*.conf" -exec basename {} \; -exec sed 's/\.conf$//' \; 2>/dev/null )
    
}

function _kerberosfiles() {
    COMPREPLY=()
    local CUR KEYS
    CUR="${COMP_WORDS[COMP_CWORD]}"
    KEYS=$(_kerberosconfig)
    COMPREPLY=( $(compgen -W "${KEYS}" -- ${CUR}) )
    return 0
}
complete -F _kerberosfiles kinit-custom
