#!/bin/bash


function _keys() {
    KEYS=""
    for KEY_DIR in ${SETPROXY_CREDS_DIRS[*]};do
        KEYS=$(find ${SETPROXY_CREDS_DIRS[*]} -type f -name "*.conf" -exec basename {} \; 2>/dev/null |sed 's/\.conf$//')
    done
    echo $KEYS
}

function _keyfiles() {
    COMPREPLY=()
    local CUR KEYS
    CUR="${COMP_WORDS[COMP_CWORD]}"
    #KEYS="$(find ${KEY_DIR}/* -type f|awk -F ${KEY_DIR}/ '{print $2}'|sed 's/\.session$//')"
    KEYS=$(_keys)
    COMPREPLY=( $(compgen -W "${KEYS}" -- ${CUR}) )
    return 0
}
complete -F _keyfiles setproxy
